# Services
services:
    maxmind.geoip:
        class:      Maxmind\Bundle\GeoipBundle\Service\GeoipManager
        arguments:  [ "@kernel" ]

    maxmind.geoip.twig_extension:
        class:      Maxmind\Bundle\GeoipBundle\Twig\GeoipExtension
        public:     false
        arguments:  [ "@maxmind.geoip" ]
        tags:
            - { name: twig.extension }
